### PR TITLE
Add support for CSAF field

### PR DESCRIPTION
**Pull request by tschmidtb51**
fixes securitytxt/securitytxt.org#92

### CODE REVIEW

**Comment by EdOverflow** [comment]
Thank you for the pull request, @tschmidtb51. This looks good to me but I will wait for @joker314 to review this if they get a chance just to make sure.

**Review by joker314 — CHANGES_REQUESTED** [review]
The changes to the YAML are correct and look good. 👍 Thank you for submitting it.

The way the form currently works is that the field names have to be listed once more in the JavaScript in order for them to be included in the output. https://github.com/securitytxt/securitytxt.org/blob/615a74fff39c36c3e46927b52c503934fc2ebba8/js/genform.js#L27-L29

However, the existing code converts camel case into hyphens, but we don't want that here (it would lead to `C-S-A-F:` instead of `CSAF:`). In the short term we could special-case the CSAF field, but I think it would be better to update the JS so this problem does not occur in the future. I will make that update in the next few days, and then we can merge this PR.

**Comment by tschmidtb51** [comment]
@joker314 Sorry for the long radio silence. I added the `id` `csaf` to be included in the output.

**Comment by tschmidtb51** [comment]
@joker314 I created #95 as replacement if you want the short term hack.

**Pull request merged**
